name: Build Augmented Steam
on:
  push:
    branches: [develop, master]
jobs:
  build-all:
    strategy:
      matrix:
        browser: [firefox, chrome, edge]
    uses: ./.github/workflows/run-build.yml
    with:
      browser: ${{ matrix.browser }}
